# Generated by Django 6.1 on 2026-08-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
