# Generated by Django 6.1 on 2026-08-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0002_chemicallevels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicallevels',
            name='percentage',
        ),
    ]
