# Generated by Django 6.1 on 2026-08-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0003_remove_chemicallevels_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicallevels',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
