# Generated by Django 6.1 on 2026-08-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0004_chemicallevels_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoItem',
        ),
        migrations.RenameField(
            model_name='chemicallevels',
            old_name='title',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='chemicallevels',
            name='percentage',
        ),
        migrations.AddField(
            model_name='chemicallevels',
            name='location',
            field=models.IntegerField(choices=[(0, 'Kitchen'), (1, 'Bar'), (2, 'Dish pit'), (3, 'Basement'), (4, 'Upstairs')], default=0),
        ),
        migrations.AddField(
            model_name='chemicallevels',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chemicallevels',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
