# Generated by Django 6.1 on 2026-08-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0005_delete_todoitem_rename_title_chemicallevels_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicallevels',
            name='location',
            field=models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bar', 'Bar'), ('Dish pit', 'Dish pit'), ('Basement', 'Basement'), ('Upstairs', 'Upstairs')], default=0),
        ),
    ]
