# Generated by Django 6.1 on 2026-08-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0006_alter_chemicallevels_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicallevels',
            name='location',
            field=models.IntegerField(choices=[(0, 'Kitchen'), (1, 'Bar'), (2, 'Dish Pit'), (3, 'Basement'), (4, 'Upstairs')], default=0),
        ),
    ]
