# Generated by Django 6.1 on 2026-08-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0007_alter_chemicallevels_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemicallevels',
            options={'ordering': ['location']},
        ),
    ]
