# Generated by Django 6.1 on 2026-08-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0008_alter_chemicallevels_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemicallevels',
            options={'ordering': ['location', 'number']},
        ),
    ]
