# Generated by Django 6.1.1 on 2026-09-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0009_alter_chemicallevels_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
