# Generated by Django 6.1 on 2026-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0010_addchemical'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_location', models.IntegerField(choices=[(0, 'Kitchen'), (1, 'Bar'), (2, 'Dish Pit'), (3, 'Basement'), (4, 'Upstairs')], default=0)),
                ('volume_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('volume_unit', models.IntegerField(choices=[(0, 'Liters'), (1, 'Gallons'), (2, 'Milliliters')], default=0)),
                ('density', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('color', models.IntegerField(choices=[(0, 'Black'), (1, 'White'), (2, 'Red'), (3, 'Orange'), (4, 'Yellow'), (5, 'Blue'), (6, 'Purple'), (7, 'Green')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='AddChemical',
        ),
        migrations.AddField(
            model_name='chemicallevels',
            name='color',
            field=models.IntegerField(choices=[(0, 'Black'), (1, 'White'), (2, 'Red'), (3, 'Orange'), (4, 'Yellow'), (5, 'Blue'), (6, 'Purple'), (7, 'Green')], default=0),
        ),
    ]
