# Generated by Django 6.1 on 2026-09-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0011_add_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicallevels',
            name='density',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='chemicallevels',
            name='volume_unit',
            field=models.IntegerField(choices=[(0, 'Liters'), (1, 'Gallons'), (2, 'Milliliters')], default=0),
        ),
        migrations.AlterField(
            model_name='chemicallevels',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
