# Generated by Django 6.1 on 2026-09-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0012_chemicallevels_from_product_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='color',
            field=models.IntegerField(choices=[(0, 'Blue'), (1, 'Orange'), (2, 'Green'), (3, 'Gray'), (4, 'Yellow'), (5, 'Purple'), (6, 'Brown'), (7, 'Pink'), (8, 'Cyan')], default=0),
        ),
        migrations.AlterField(
            model_name='chemicallevels',
            name='color',
            field=models.IntegerField(choices=[(0, 'Blue'), (1, 'Orange'), (2, 'Green'), (3, 'Gray'), (4, 'Yellow'), (5, 'Purple'), (6, 'Brown'), (7, 'Pink'), (8, 'Cyan')], default=0),
        ),
    ]
