# Generated by Django 6.1 on 2026-09-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0014_add_white_red_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicallevels',
            name='current_weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
