# Generated by Django 6.1 on 2026-09-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0015_add_current_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_location', models.IntegerField(choices=[(0, 'Kitchen'), (1, 'Bar'), (2, 'Dish Pit'), (3, 'Basement'), (4, 'Upstairs')], default=0)),
                ('product_number', models.IntegerField(default=0)),
                ('volume_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('volume_unit', models.IntegerField(choices=[(0, 'Liters'), (1, 'Gallons'), (2, 'Milliliters')], default=0)),
                ('density', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('color', models.IntegerField(choices=[(0, 'Blue'), (1, 'Orange'), (2, 'Green'), (3, 'Gray'), (4, 'Yellow'), (5, 'Purple'), (6, 'Brown'), (7, 'Pink'), (8, 'Cyan'), (9, 'White'), (10, 'Red')], default=0)),
                ('current_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_location', 'product_number'],
            },
        ),
        migrations.DeleteModel(
            name='AddProduct',
        ),
        migrations.DeleteModel(
            name='ChemicalLevels',
        ),
    ]
