# Generated by Django 6.1 on 2026-09-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appidea1', '0016_rename_to_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_location', 'product_name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_number',
        ),
    ]
